# Dockerfile_dagster
FROM python:3.10-slim

# Install needed packages for webserver + daemon
RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

# Set $DAGSTER_HOME and copy dagster.yaml + workspace.yaml
ENV DAGSTER_HOME=/opt/dagster/dagster_home
RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

# Use /opt/dagster/dagster_home as the working dir
WORKDIR $DAGSTER_HOME
