# Dockerfile_user_code
FROM python:3.10-slim

# Install packages needed for your user code
RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker

# Copy your user code
WORKDIR /opt/dagster/app
COPY pipeline/ /opt/dagster/app

# Expose port 4000 for the code server
EXPOSE 4000

# By default, run the code server
CMD ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-f", "definitions.py"]
